### ISSUE TITLE
core user not getting created by anaconda

### ISSUE THREAD

**Issue by dustymabe** [cgwalters/fedora-coreos-config#4]
from anaconda.log:

```
00:58:21,447 WRN kickstart.kickstart.user: Invalid groups ['wheel', 'sudo', 'adm', 'systemd-journal']
```

**Comment by cgwalters** [comment]
Fixed!

**Comment by cgwalters** [comment]
Hey so Dusty...why did you reference a `sudo` group? My [commit message](https://github.com/coreos/fedora-coreos-config/commit/685f2137ddaa5a66f1f9aa6822fd1c584c5f62f6) says it was because Container Linux had it but...how does CL relate to Anaconda here?

Was something actually needing `sudo`?

Anyways nowadays: https://gitlab.com/fedora/bootc/base-images/-/issues/41

**Comment by cgwalters** [comment]
After some more digging, I found the reason: https://github.com/openshift/os/issues/96#issuecomment-398561810

**Comment by dustymabe** [comment]
Ha. Hopefully nothing depends on me remembering why I did something in 2018 :)
